# Global params
loop_rate: 100
log_location: /home/jwhite/bldc/pff_equipment_testing

# Arduino params
arduino_device_file: /dev/pff/arduino_uno

# Force gauge params
force_gauge_device_file: /dev/pff/force_gauge

# Vesc params
port: /dev/pff/vesc
motor_namespace: linkage
feedback_topic: feedback
status_topic: status
cmd_topic: cmd