# Global params
loop_rate: 100
log_location: ~/.ros/

# Arduino params
arduino_device_file: /dev/ttyUSB0

# Force gauge params
force_gauge_device_file: /dev/ttyACM0

# Vesc params
port: /dev/ttyUSB1
motor_namespace: linkage
feedback_topic: feedback
status_topic: status
cmd_topic: cmd